#!/usr/bin/env python3
"""Build helpers for the TallieLight UI test harness.

Called by build-test-page.sh with one of two subcommands:

  refresh-style <out> <ref> <color_h> <style1_h> <style2_h> <style3_h>
    Parse four Tasmota CSS header files (fetched from GitHub by the shell
    script via curl) and write tasmota_style.html.

    The %06x color placeholders in the source are filled at runtime by the
    device theme; this script substitutes the Tasmota dark-theme defaults
    from tasmota/my_user_config.h so the harness matches a real device.

  build <ui> <tasmota_style> <template> <out>
    Assemble tallielight_ui_test.html from three source files by substituting
    placeholders in test_harness.html:
      __TASMOTA_STYLE__  →  <style>…</style> block from tasmota_style.html
      __UI_BODY__        →  full contents of tallielight_ui.html
"""
import re
import sys
from pathlib import Path

def relpath(p):
    try:
        return Path(p).relative_to(Path.cwd())
    except ValueError:
        return Path(p)

# Dark-theme defaults from tasmota/my_user_config.h (WebColor1–20).
# Order matches the %06x placeholders in HTTP_HEAD_STYLE_ROOT_COLOR.h:
#   c_bg, c_frm, c_ttl, c_txt, c_txtwrn, c_txtscc,
#   c_btn, c_btnoff, c_btntxt, c_btnhvr, c_btnrst, c_btnrsthvr,
#   c_btnsv, c_btnsvhvr, c_in, c_intxt, c_csl, c_csltxt, c_tab, c_tabtxt
DARK_COLORS = [
    "252525",  # c_bg         background
    "4f4f4f",  # c_frm        form background
    "eaeaea",  # c_ttl        title text
    "eaeaea",  # c_txt        global text
    "ff5661",  # c_txtwrn     warning text
    "008000",  # c_txtscc     success text
    "1fa3ec",  # c_btn        button
    "08405e",  # c_btnoff     button off
    "faffff",  # c_btntxt     button text
    "0e70a4",  # c_btnhvr     button hover
    "d43535",  # c_btnrst     reset button
    "931f1f",  # c_btnrsthvr  reset button hover
    "47c266",  # c_btnsv      save button
    "5aaf6f",  # c_btnsvhvr   save button hover
    "dddddd",  # c_in         input background
    "000000",  # c_intxt      input text
    "1f1f1f",  # c_csl        console background
    "65c115",  # c_csltxt     console text
    "999999",  # c_tab        timer tab background
    "faffff",  # c_tabtxt     timer tab text
]


def extract_strings(src):
    """Concatenate all C string literals, stripping // and /* */ comments."""
    src = re.sub(r"//[^\n]*", "", src)
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.DOTALL)
    return "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', src))


def cmd_refresh_style(args):
    out_path, ref, color_h, style1_h, style2_h, style3_h = \
        Path(args[0]), args[1], args[2], args[3], args[4], args[5]

    print(f"Parsing Tasmota CSS (ref={ref})…")

    color_raw = extract_strings(color_h)

    # Substitute %06x placeholders with dark-theme hex values.
    color_iter = iter(DARK_COLORS)
    def sub_color(_m):
        try:
            return next(color_iter)
        except StopIteration:
            sys.exit("ERROR: more %06x placeholders than expected — check DARK_COLORS list")
    color_css = re.sub(r"%06x", sub_color, color_raw)

    # Concatenate: :root vars + base rules + button/link rules + </style>.
    # STYLE3 also contains </head><body>… — we only want the leading </style>.
    style3_raw = extract_strings(style3_h)
    closing = style3_raw[:style3_raw.index("</style>") + len("</style>")]

    combined = color_css + extract_strings(style1_h) + extract_strings(style2_h) + closing

    if not (combined.startswith("<style>") and combined.endswith("</style>")):
        sys.exit(f"ERROR: unexpected CSS structure from ref '{ref}' — source format may have changed")

    header = f"<!-- Generated by tests/web/build-test-page.sh from Tasmota GitHub ref={ref}. Do not edit. -->\n"
    out_path.write_text(header + combined + "\n")
    print(f"wrote {relpath(out_path)}  ({len(combined)} bytes)")


def cmd_build(args):
    ui_path, tasmota_path, template_path, out_path = (Path(p) for p in args)

    ui       = ui_path.read_text()
    template = template_path.read_text()

    # Extract the <style>…</style> block. tasmota_style.html has a generation
    # comment followed by a single <style> tag — we want just the tag.
    tasmota_src = tasmota_path.read_text()
    m = re.search(r"<style>.*?</style>", tasmota_src, re.DOTALL)
    if not m:
        sys.exit(f"no <style> block found in {tasmota_path}")

    header = "<!-- Generated by tests/web/build-test-page.sh. Do not edit. -->\n"
    out = template.replace("__TASMOTA_STYLE__", m.group(0)).replace("__UI_BODY__", ui)
    out_path.write_text(header + out)
    print(f"wrote {relpath(out_path)}")


COMMANDS = {"refresh-style": cmd_refresh_style, "build": cmd_build}

if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
    sys.exit(f"usage: {sys.argv[0]} ({' | '.join(COMMANDS)}) ...")

COMMANDS[sys.argv[1]](sys.argv[2:])
